-- Generated from "danh sach ma truong moet.xlsx" on 2026-09-08.
-- Source rows are treated strictly as data; 347 unique Quang Ninh school codes were validated.
begin;

with source(
  ma_truong, ten, loai_hinh_dao_tao, loai_hinh_truong, nhom_cap_hoc,
  phuong_xa, loai_hinh, cap_hoc, cong_lap
) as (
  values
    ('2200004001', 'Liên cấp Quốc tế Singapore', 'Tư thục', 'TH-THCS-THPT', 'MN - PT', 'Phường Bãi Cháy', 'pho_thong', array['tieu_hoc', 'thcs', 'thpt']::public.cap_hoc[], false),
    ('22195425', 'Mầm non - Tiểu học Hội nhập Quốc tế iSchool Cẩm Phả', 'Tư thục', 'TH', 'MN - TH', 'Phường Cẩm Phả', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], false),
    ('22202301', 'Mầm non Ba Chẽ', 'Công lập', 'MN', 'Mầm non', 'Xã Ba Chẽ', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22193326', 'Mầm non Bãi Cháy', 'Công lập', 'MN', 'Mầm non', 'Phường Bãi Cháy', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22205323', 'Mầm non Bình Dương', 'Công lập', 'MN', 'Mầm non', 'Phường An Sinh', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22198301', 'Mầm non Bình Liêu 1', 'Công lập', 'MN', 'Mầm non', 'Xã Bình Liêu', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22198305', 'Mầm non Bình Liêu 2', 'Công lập', 'MN', 'Mầm non', 'Xã Bình Liêu', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22194309', 'Mầm non Bình Ngọc', 'Công lập', 'MN', 'Mầm non', 'Phường Móng Cái 1', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22193308', 'Mầm non Cao Xanh', 'Công lập', 'MN', 'Mầm non', 'Phường Cao Xanh', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22203305', 'Mầm non Cái Rồng', 'Công lập', 'MN', 'Mầm non', 'Đặc khu Vân Đồn', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22207303', 'Mầm non Cô Tô', 'Công lập', 'MN', 'Mầm non', 'Đặc khu Cô Tô', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22195303', 'Mầm non Cẩm Phú', 'Công lập', 'MN', 'Mầm non', 'Phường Cửa Ông', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22195306', 'Mầm non Cẩm Phả', 'Công lập', 'MN', 'Mầm non', 'Phường Cẩm Phả', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22195304', 'Mầm non Cẩm Sơn', 'Công lập', 'MN', 'Mầm non', 'Phường Cửa Ông', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22195302', 'Mầm non Cửa Ông', 'Công lập', 'MN', 'Mầm non', 'Phường Cửa Ông', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22193338', 'Mầm non Dongsim - Hạ Long', 'Tư thục', 'MN', 'Mầm non', 'Phường Bãi Cháy', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22200306', 'Mầm non Dực Yên', 'Công lập', 'MN', 'Mầm non', 'Xã Quảng Tân', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22205330', 'Mầm non EduKids', 'Tư thục', 'MN', 'Mầm non', 'Phường Mạo Khê', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22196318', 'Mầm non Edukids - Uông Bí', 'Tư thục', 'MN', 'Mầm non', 'Phường Uông Bí', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22193335', 'Mầm non Family', 'Tư thục', 'MN', 'Mầm non', 'Phường Hồng Gai', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22206321', 'Mầm non Hiệp Hòa', 'Công lập', 'MN', 'Mầm non', 'Phường Hiệp Hòa', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22193336', 'Mầm non Hoa Anh Đào - Hạ Long', 'Tư thục', 'MN', 'Mầm non', 'Phường Hồng Gai', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22201320', 'Mầm non Hoa Hồng - Hải Hà', 'Tư thục', 'MN', 'Mầm non', 'Xã Quảng Hà', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22194304', 'Mầm non Hoa Hồng - Móng Cái', 'Tư thục', 'MN', 'Mầm non', 'Phường Móng Cái 1', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22195313', 'Mầm non Hoa Hồng - Quang Hanh', 'Công lập', 'MN', 'Mầm non', 'Phường Quang Hanh', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22206301', 'Mầm non Hoa Hồng - Quảng Yên', 'Công lập', 'MN', 'Mầm non', 'Phường Quảng Yên', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22196308', 'Mầm non Hoa Lan - Uông Bí', 'Tư thục', 'MN', 'Mầm non', 'Phường Uông Bí', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22194305', 'Mầm non Hoa Mai', 'Công lập', 'MN', 'Mầm non', 'Phường Móng Cái 1', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22199302', 'Mầm non Hoa Mai - Tiên Yên', 'Tư thục', 'MN', 'Mầm non', 'Xã Tiên Yên', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22195309', 'Mầm non Hoa Sen', 'Công lập', 'MN', 'Mầm non', 'Phường Cẩm Phả', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22194320', 'Mầm non Hoa Sen Montessori - Móng Cái', 'Tư thục', 'MN', 'Mầm non', 'Phường Móng Cái 2', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22205317', 'Mầm non Hoàng Quế', 'Công lập', 'MN', 'Mầm non', 'Phường Hoàng Quế', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22198302', 'Mầm non Hoành Mô', 'Công lập', 'MN', 'Mầm non', 'Xã Hoành Mô', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22206302', 'Mầm non Hà An', 'Công lập', 'MN', 'Mầm non', 'Phường Hà An', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22193310', 'Mầm non Hà Lầm', 'Công lập', 'MN', 'Mầm non', 'Phường Hà Lầm', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22193312', 'Mầm non Hà Tu', 'Công lập', 'MN', 'Mầm non', 'Phường Hà Tu', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22205312', 'Mầm non Hưng Đạo', 'Công lập', 'MN', 'Mầm non', 'Phường Đông Triều', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22203302', 'Mầm non Hạ Long', 'Công lập', 'MN', 'Mầm non', 'Đặc khu Vân Đồn', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22193334', 'Mầm non Hạnh phúc', 'Công lập', 'MN', 'Mầm non', 'Phường Hạ Long', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22195316', 'Mầm non Hải Hòa', 'Công lập', 'MN', 'Mầm non', 'Xã Hải Hòa', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22199308', 'Mầm non Hải Lạng', 'Công lập', 'MN', 'Mầm non', 'Xã Hải Lạng', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22194312', 'Mầm non Hải Ninh', 'Công lập', 'MN', 'Mầm non', 'Xã Hải Ninh', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22194313', 'Mầm non Hải Sơn', 'Công lập', 'MN', 'Mầm non', 'Xã Hải Sơn', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22193305', 'Mầm non Hồng Gai', 'Công lập', 'MN', 'Mầm non', 'Phường Hồng Gai', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22193321', 'Mầm non InterKids - Hạ Long', 'Tư thục', 'MN', 'Mầm non', 'Phường Việt Hưng', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22194319', 'Mầm non Ka Long', 'Tư thục', 'MN', 'Mầm non', 'Phường Móng Cái 2', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22204312', 'Mầm non Kỳ Thượng', 'Công lập', 'MN', 'Mầm non', 'Xã Kỳ Thượng', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('195DL090', 'Mầm non Litle House Cẩm Bình', 'Tư thục', 'MN', 'Mầm non', 'Phường Cẩm Phả', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22195190', 'Mầm non Little House', 'Tư thục', 'MN', 'Mầm non', 'Phường Quang Hanh', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22193325', 'Mầm non Little House Hạ Long', 'Tư thục', 'MN', 'Mầm non', 'Phường Hạ Long', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22206318', 'Mầm non Liên Hòa', 'Công lập', 'MN', 'Mầm non', 'Phường Liên Hòa', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22206310', 'Mầm non Liên Vị', 'Công lập', 'MN', 'Mầm non', 'Phường Liên Hòa', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22202305', 'Mầm non Lương Mông', 'Công lập', 'MN', 'Mầm non', 'Xã Lương Minh', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22198304', 'Mầm non Lục Hồn', 'Công lập', 'MN', 'Mầm non', 'Xã Lục Hồn', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22194316', 'Mầm non Móng Cái 2', 'Công lập', 'MN', 'Mầm non', 'Phường Móng Cái 2', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22194301', 'Mầm non Móng Cái 3', 'Công lập', 'MN', 'Mầm non', 'Phường Móng Cái 3', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22195301', 'Mầm non Mông Dương', 'Công lập', 'MN', 'Mầm non', 'Phường Mông Dương', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22205327', 'Mầm non Mạo Khê', 'Công lập', 'MN', 'Mầm non', 'Phường Mạo Khê', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22205313', 'Mầm non Mạo Khê I', 'Công lập', 'MN', 'Mầm non', 'Phường Mạo Khê', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22205315', 'Mầm non Mạo Khê II', 'Công lập', 'MN', 'Mầm non', 'Phường Mạo Khê', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22205322', 'Mầm non Nguyễn Huệ', 'Công lập', 'MN', 'Mầm non', 'Phường Đông Triều', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22203312', 'Mầm non Ngọc Vừng', 'Công lập', 'MN', 'Mầm non', 'Đặc khu Vân Đồn', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('2219301001', 'Mầm non Những Ngôi Sao Nhỏ - Bãi Cháy', 'Tư thục', 'MN', 'Mầm non', 'Phường Bãi Cháy', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('2219401002', 'Mầm non Olympia - Móng Cái', 'Tư thục', 'MN', 'Mầm non', 'Phường Móng Cái 3', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('2219401001', 'Mầm non Oscar - MóngCái', 'Tư thục', 'MN', 'Mầm non', 'Phường Móng Cái 1', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22206308', 'Mầm non Phong Cốc I', 'Công lập', 'MN', 'Mầm non', 'Phường Phong Cốc', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22206316', 'Mầm non Phong Cốc II', 'Công lập', 'MN', 'Mầm non', 'Phường Phong Cốc', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22193322', 'Mầm non Phương Huyền - Hạ Long', 'Tư thục', 'MN', 'Mầm non', 'Phường Bãi Cháy', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22196302', 'Mầm non Phương Nam', 'Công lập', 'MN', 'Mầm non', 'Phường Yên Tử', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22196303', 'Mầm non Phương Đông', 'Công lập', 'MN', 'Mầm non', 'Phường Yên Tử', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22205319', 'Mầm non Phạm Hồng Thái', 'Công lập', 'MN', 'Mầm non', 'Phường Hoàng Quế', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22203304', 'Mầm non Quan Lạn', 'Công lập', 'MN', 'Mầm non', 'Đặc khu Vân Đồn', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22195312', 'Mầm non Quang Hanh', 'Công lập', 'MN', 'Mầm non', 'Phường Quang Hanh', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22201301', 'Mầm non Quảng Hà', 'Công lập', 'MN', 'Mầm non', 'Xã Quảng Hà', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22204306', 'Mầm non Quảng La', 'Công lập', 'MN', 'Mầm non', 'Xã Quảng La', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22201309', 'Mầm non Quảng Long', 'Công lập', 'MN', 'Mầm non', 'Xã Đường Hoa', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22201307', 'Mầm non Quảng Minh', 'Công lập', 'MN', 'Mầm non', 'Xã Quảng Hà', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22201308', 'Mầm non Quảng Phong', 'Công lập', 'MN', 'Mầm non', 'Xã Quảng Hà', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22201303', 'Mầm non Quảng Thịnh', 'Công lập', 'MN', 'Mầm non', 'Xã Quảng Đức', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22200309', 'Mầm non Quảng Tân', 'Công lập', 'MN', 'Mầm non', 'Xã Quảng Tân', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22206322', 'Mầm non Quảng Yên', 'Tư thục', 'MN', 'Mầm non', 'Phường Quảng Yên', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22201317', 'Mầm non Quảng Đức', 'Công lập', 'MN', 'Mầm non', 'Xã Quảng Đức', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22193339', 'Mầm non Quốc tế UK', 'Tư thục', 'MN', 'Mầm non', 'Phường Hạ Long', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22195111', 'Mầm non Quốc tế thiếu nhi 1/6', 'Tư thục', 'MN', 'Mầm non', 'Phường Cửa Ông', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22193340', 'Mầm non STEAMeQ Hạ Long', 'Tư thục', 'MN', 'Mầm non', 'Phường Hạ Long', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('2206685001', 'Mầm non Sasuke Hạ Long', 'Tư thục', 'MN', 'Mầm non', 'Phường Hạ Long', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('2219601001', 'Mầm non Song ngữ Montessori Vân Anh', 'Tư thục', 'MN', 'Mầm non', 'Phường Uông Bí', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22206312', 'Mầm non Sông Khoai', 'Công lập', 'MN', 'Mầm non', 'Phường Hiệp Hòa', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22204303', 'Mầm non Sơn Dương', 'Công lập', 'MN', 'Mầm non', 'Phường Hoành Bồ', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22193333', 'Mầm non Thanh Bình', 'Tư thục', 'MN', 'Mầm non', 'Phường Bãi Cháy', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22196312', 'Mầm non Thượng Yên Công', 'Công lập', 'MN', 'Mầm non', 'Phường Yên Tử', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22204304', 'Mầm non Thống Nhất', 'Công lập', 'MN', 'Mầm non', 'Xã Thống Nhất', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22199301', 'Mầm non Tiên Yên', 'Công lập', 'MN', 'Mầm non', 'Xã Tiên Yên', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22205309', 'Mầm non Tràng An', 'Công lập', 'MN', 'Mầm non', 'Phường Bình Khê', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22205307', 'Mầm non Tràng Lương', 'Công lập', 'MN', 'Mầm non', 'Phường Bình Khê', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22196314', 'Mầm non Trưng Vương', 'Công lập', 'MN', 'Mầm non', 'Phường Vàng Danh', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22204301', 'Mầm non Trới', 'Công lập', 'MN', 'Mầm non', 'Phường Hoành Bồ', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22193327', 'Mầm non Tuần Châu', 'Công lập', 'MN', 'Mầm non', 'Phường Tuần Châu', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22200312', 'Mầm non Tuổi thơ - Đầm Hà', 'Tư thục', 'MN', 'Mầm non', 'Xã Đầm Hà', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22205329', 'Mầm non Tư thục Huy Hoàng', 'Tư thục', 'MN', 'Mầm non', 'Phường Mạo Khê', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22196304', 'Mầm non Uông Bí', 'Công lập', 'MN', 'Mầm non', 'Phường Uông Bí', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22205304', 'Mầm non Việt Dân', 'Công lập', 'MN', 'Mầm non', 'Phường An Sinh', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22193302', 'Mầm non Việt Hưng', 'Công lập', 'MN', 'Mầm non', 'Phường Việt Hưng', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22196306', 'Mầm non Vàng Danh', 'Công lập', 'MN', 'Mầm non', 'Phường Vàng Danh', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22206323', 'Mầm non Vân Anh - Quảng Yên', 'Tư thục', 'MN', 'Mầm non', 'Phường Quảng Yên', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22194315', 'Mầm non Vĩnh Thực', 'Công lập', 'MN', 'Mầm non', 'Xã Vĩnh Thực', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22204308', 'Mầm non Vũ Oai', 'Công lập', 'MN', 'Mầm non', 'Xã Thống Nhất', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('2220301001', 'Mầm non chất lượng cao Việt Úc Vân Đồn', 'Tư thục', 'MN', 'Mầm non', 'Đặc khu Vân Đồn', 'mam_non', array['mam_non']::public.cap_hoc[], false),
    ('22200305', 'Mầm non xã Đầm Hà', 'Công lập', 'MN', 'Mầm non', 'Xã Đầm Hà', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22199310', 'Mầm non Điền Xá', 'Công lập', 'MN', 'Mầm non', 'Xã Điền Xá', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22203301', 'Mầm non Đoàn Kết', 'Công lập', 'MN', 'Mầm non', 'Đặc khu Vân Đồn', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22206313', 'Mầm non Đông Mai', 'Công lập', 'MN', 'Mầm non', 'Phường Đông Mai', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22199305', 'Mầm non Đông Ngũ', 'Công lập', 'MN', 'Mầm non', 'Xã Đông Ngũ', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22201315', 'Mầm non Đường Hoa', 'Công lập', 'MN', 'Mầm non', 'Xã Đường Hoa', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22200310', 'Mầm non Đại Bình', 'Công lập', 'MN', 'Mầm non', 'Xã Đầm Hà', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22200301', 'Mầm non Đầm Hà I', 'Công lập', 'MN', 'Mầm non', 'Xã Đầm Hà', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22202302', 'Mầm non Đồn Đạc', 'Công lập', 'MN', 'Mầm non', 'Xã Ba Chẽ', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22204309', 'Mầm non Đồng Sơn', 'Công lập', 'MN', 'Mầm non', 'Xã Lương Minh', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('22205310', 'Mầm non Đức Chính', 'Công lập', 'MN', 'Mầm non', 'Phường Đông Triều', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('2219601006', 'Mẫu giáo Thực hành sư phạm', 'Công lập', 'MN', 'Mầm non', 'Phường Vàng Danh', 'mam_non', array['mam_non']::public.cap_hoc[], true),
    ('221980', 'PT DT nội trú Bình Liêu', 'Công lập', 'THCS', 'THCS', 'Xã Bình Liêu', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('222020', 'PTDT Nội Trú Ba Chẽ', 'Công lập', 'THCS', 'THCS', 'Xã Ba Chẽ', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('220000', 'PTDT Nội trú THCS và THPT Tỉnh Quảng Ninh', 'Công lập', 'THCS-THPT', 'Trung học', 'Phường Hạ Long', 'pho_thong', array['thcs', 'thpt']::public.cap_hoc[], true),
    ('222010', 'PTDT nội trú THCS Hải Hà', 'Công lập', 'THCS', 'THCS', 'Xã Quảng Hà', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22201509', 'PTNT TH và THCS Quảng Sơn', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Đường Hoa', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22201512', 'PTNT TH và THCS Quảng Đức', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Quảng Đức', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22205504', 'TH và THCS An Sinh', 'Công lập', 'TH-THCS', 'PTCS', 'Phường An Sinh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22195511', 'TH và THCS Bái Tử Long', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Quang Hanh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22205502', 'TH và THCS Bình Dương', 'Công lập', 'TH-THCS', 'PTCS', 'Phường An Sinh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22205523', 'TH và THCS Bình Khê', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Bình Khê', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22198501', 'TH và THCS Bình Liêu', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Bình Liêu', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22196501', 'TH và THCS Bắc Sơn', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Vàng Danh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22193509', 'TH và THCS Cao Xanh', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Cao Xanh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22201605', 'TH và THCS Cái Chiên', 'Công lập', 'TH-THCS', 'MN - PTCS', 'Xã Cái Chiên', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22207501', 'TH và THCS Cô Tô', 'Công lập', 'TH-THCS', 'PTCS', 'Đặc khu Cô Tô', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22206405', 'TH và THCS Hiệp Hòa', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Hiệp Hòa', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22198506', 'TH và THCS Hoành Mô', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Hoành Mô', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22199604', 'TH và THCS Hà Lâu', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Điền Xá', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22193515', 'TH và THCS Hà Tu', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Hà Tu', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22198507', 'TH và THCS Húc Động', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Bình Liêu', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22194507', 'TH và THCS Hải Hòa', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Móng Cái 1', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22195602', 'TH và THCS Hải Hòa', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Hải Hòa', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22199504', 'TH và THCS Hải Lạng', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Hải Lạng', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22194703', 'TH và THCS Hải Sơn', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Hải Sơn', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22194513', 'TH và THCS Hải Tiến', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Hải Ninh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22194506', 'TH và THCS Hải Xuân', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Móng Cái 1', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22194502', 'TH và THCS Hải Yên', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Móng Cái 3', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22194501', 'TH và THCS Hải Đông', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Móng Cái 3', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22204607', 'TH và THCS Kỳ Thượng', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Kỳ Thượng', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22202601', 'TH và THCS Lương Mông', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Lương Minh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22198502', 'TH và THCS Lục Hồn', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Lục Hồn', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22203605', 'TH và THCS Minh Châu', 'Công lập', 'TH-THCS', 'PTCS', 'Đặc khu Vân Đồn', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22206507', 'TH và THCS Minh Thành', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Đông Mai', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22196504', 'TH và THCS Nam Khê', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Vàng Danh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22202604', 'TH và THCS Nam Sơn', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Ba Chẽ', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22196510', 'TH và THCS Nguyễn Văn Cừ', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Vàng Danh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22203606', 'TH và THCS Ngọc Vừng', 'Công lập', 'TH-THCS', 'PTCS', 'Đặc khu Vân Đồn', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22199503', 'TH và THCS Phong Dụ', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Tiên Yên', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22206512', 'TH và THCS Phong Hải', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Liên Hòa', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22196508', 'TH và THCS Phương Nam', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Yên Tử', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22196507', 'TH và THCS Phương Đông', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Yên Tử', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22195513', 'TH và THCS Quang Hanh', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Quang Hanh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22200504', 'TH và THCS Quảng An', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Quảng Tân', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22201503', 'TH và THCS Quảng Chính', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Quảng Hà', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22201504', 'TH và THCS Quảng Hà II', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Quảng Hà', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22204603', 'TH và THCS Quảng La', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Quảng La', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22200508', 'TH và THCS Quảng Lâm', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Quảng Tân', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22201502', 'TH và THCS Quảng Minh', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Quảng Hà', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22194512', 'TH và THCS Quảng Nghĩa', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Hải Ninh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22201508', 'TH và THCS Quảng Phong', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Quảng Hà', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22200503', 'TH và THCS Quảng Tân', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Quảng Tân', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22201505', 'TH và THCS Quảng Đức', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Quảng Đức', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22196603', 'TH và THCS Quốc tế Stephen Hawking', 'Tư thục', 'TH-THCS', 'PTCS', 'Phường Uông Bí', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], false),
    ('22195514', 'TH và THCS Suối Khoáng', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Quang Hanh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22204505', 'TH và THCS Sơn Dương', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Hoành Bồ', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22202602', 'TH và THCS Thanh Lâm', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Kỳ Thượng', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22207503', 'TH và THCS Thanh Lân', 'Công lập', 'TH-THCS', 'PTCS', 'Đặc khu Cô Tô', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22204503', 'TH và THCS Thống Nhất', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Thống Nhất', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22199502', 'TH và THCS Tiên Lãng', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Tiên Yên', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22206515', 'TH và THCS Tiền An', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Quảng Yên', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22206601', 'TH và THCS Tiền Phong', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Liên Hòa', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22194508', 'TH và THCS Trà Cổ', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Móng Cái 1', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22205507', 'TH và THCS Tràng An', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Bình Khê', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22196503', 'TH và THCS Trưng Vương', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Vàng Danh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22193601', 'TH và THCS Tuần Châu', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Tuần Châu', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22204506', 'TH và THCS Tân Dân', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Quảng La', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22196509', 'TH và THCS Uông Bí', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Uông Bí', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22205503', 'TH và THCS Việt Dân', 'Công lập', 'TH-THCS', 'PTCS', 'Phường An Sinh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22193502', 'TH và THCS Việt Hưng', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Việt Hưng', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22198505', 'TH và THCS Vô Ngại', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Bình Liêu', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22194511', 'TH và THCS Vĩnh Thực', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Vĩnh Thực', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22204605', 'TH và THCS Vũ Oai', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Thống Nhất', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22203608', 'TH và THCS Vạn Yên', 'Công lập', 'TH-THCS', 'PTCS', 'Đặc khu Vân Đồn', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22196502', 'TH và THCS Yên Tử', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Yên Tử', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22199603', 'TH và THCS Điền Xá', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Điền Xá', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22206506', 'TH và THCS Đông Mai', 'Công lập', 'TH-THCS', 'PTCS', 'Phường Đông Mai', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22199505', 'TH và THCS Đông Ngũ', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Đông Ngũ', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22202501', 'TH và THCS Đạp Thanh', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Kỳ Thượng', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22204606', 'TH và THCS Đồng Sơn', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Lương Minh', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22207502', 'TH và THCS Đồng Tiến', 'Công lập', 'TH-THCS', 'PTCS', 'Đặc khu Cô Tô', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22198503', 'TH và THCS Đồng Tâm', 'Công lập', 'TH-THCS', 'PTCS', 'Xã Lục Hồn', 'pho_thong', array['tieu_hoc', 'thcs']::public.cap_hoc[], true),
    ('22000717', 'TH, THCS và THPT Lê Thánh Tông', 'Tư thục', 'TH-THCS-THPT', 'Phổ thông', 'Phường Hạ Long', 'pho_thong', array['tieu_hoc', 'thcs', 'thpt']::public.cap_hoc[], false),
    ('22194321', 'TH, THCS và THPT Marie Curie Móng Cái', 'Tư thục', 'TH-THCS-THPT', 'Phổ thông', 'Phường Móng Cái 2', 'pho_thong', array['tieu_hoc', 'thcs', 'thpt']::public.cap_hoc[], false),
    ('22000905', 'TH, THCS và THPT Nguyễn Bỉnh Khiêm', 'Tư thục', 'TH-THCS-THPT', 'Phổ thông', 'Phường Việt Hưng', 'pho_thong', array['tieu_hoc', 'thcs', 'thpt']::public.cap_hoc[], false),
    ('22000907', 'TH, THCS và THPT Quốc Tế Song Ngữ Học Viện Anh Quốc - UK Academy', 'Tư thục', 'TH-THCS-THPT', 'Phổ thông', 'Phường Hạ Long', 'pho_thong', array['tieu_hoc', 'thcs', 'thpt']::public.cap_hoc[], false),
    ('22000902', 'TH, THCS và THPT Trần Hưng Đạo', 'Tư thục', 'TH-THCS-THPT', 'Phổ thông', 'Phường Mạo Khê', 'pho_thong', array['tieu_hoc', 'thcs', 'thpt']::public.cap_hoc[], false),
    ('22000904', 'TH, THCS và THPT Việt Nam Singapore', 'Tư thục', 'TH-THCS-THPT', 'Phổ thông', 'Phường Bãi Cháy', 'pho_thong', array['tieu_hoc', 'thcs', 'thpt']::public.cap_hoc[], false),
    ('22000901', 'TH, THCS và THPT Văn Lang', 'Tư thục', 'TH-THCS-THPT', 'Phổ thông', 'Phường Hồng Gai', 'pho_thong', array['tieu_hoc', 'thcs', 'thpt']::public.cap_hoc[], false),
    ('22000737', 'TH, THCS và THPT Yên Hưng', 'Tư thục', 'TH-THCS-THPT', 'Phổ thông', 'Phường Quảng Yên', 'pho_thong', array['tieu_hoc', 'thcs', 'thpt']::public.cap_hoc[], false),
    ('22000903', 'TH, THCS và THPT Đoàn Thị Điểm Hạ Long', 'Tư thục', 'TH-THCS-THPT', 'Phổ thông', 'Phường Cao Xanh', 'pho_thong', array['tieu_hoc', 'thcs', 'thpt']::public.cap_hoc[], false),
    ('22196602', 'TH,THCS và THPT Thực hành Sư phạm', 'Công lập', 'TH-THCS-THPT', 'Phổ thông', 'Phường Vàng Danh', 'pho_thong', array['tieu_hoc', 'thcs', 'thpt']::public.cap_hoc[], true),
    ('22202502', 'THCS Ba Chẽ', 'Công lập', 'THCS', 'THCS', 'Xã Ba Chẽ', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22193516', 'THCS Bãi Cháy', 'Công lập', 'THCS', 'THCS', 'Phường Bãi Cháy', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22195518', 'THCS Chu Văn An', 'Công lập', 'THCS', 'THCS', 'Phường Cẩm Phả', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22203504', 'THCS Cái Rồng', 'Công lập', 'THCS', 'THCS', 'Đặc khu Vân Đồn', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22195510', 'THCS Cẩm Phả', 'Công lập', 'THCS', 'THCS', 'Phường Cẩm Phả', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22195502', 'THCS Cửa Ông', 'Công lập', 'THCS', 'THCS', 'Phường Cửa Ông', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22206503', 'THCS Hiệp Hòa', 'Công lập', 'THCS', 'THCS', 'Phường Hiệp Hòa', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22205520', 'THCS Hoàng Quế', 'Công lập', 'THCS', 'THCS', 'Phường Hoàng Quế', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22206509', 'THCS Hà An', 'Công lập', 'THCS', 'THCS', 'Phường Hà An', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22194510', 'THCS Hòa Lạc', 'Công lập', 'THCS', 'THCS', 'Phường Móng Cái 1', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22205511', 'THCS Hưng Đạo', 'Công lập', 'THCS', 'THCS', 'Phường Đông Triều', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22203502', 'THCS Hạ Long', 'Công lập', 'THCS', 'THCS', 'Đặc khu Vân Đồn', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22193513', 'THCS Lê Hồng Phong', 'Công lập', 'THCS', 'THCS', 'Phường Hạ Long', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22193505', 'THCS Lê Văn Tám', 'Công lập', 'THCS', 'THCS', 'Phường Hồng Gai', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22195504', 'THCS Lý Tự Trọng', 'Công lập', 'THCS', 'THCS', 'Phường Cửa Ông', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22194504', 'THCS Móng Cái 2', 'Công lập', 'THCS', 'THCS', 'Phường Móng Cái 2', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22195501', 'THCS Mông Dương', 'Công lập', 'THCS', 'THCS', 'Phường Mông Dương', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22205514', 'THCS Mạo Khê', 'Công lập', 'THCS', 'THCS', 'Phường Mạo Khê', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22205512', 'THCS Mạo Khê I', 'Công lập', 'THCS', 'THCS', 'Phường Mạo Khê', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22205522', 'THCS Mạo Khê II', 'Công lập', 'THCS', 'THCS', 'Phường Mạo Khê', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22195507', 'THCS Nam Hải', 'Công lập', 'THCS', 'THCS', 'Phường Cẩm Phả', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22205509', 'THCS Nguyễn Du', 'Công lập', 'THCS', 'THCS', 'Phường Đông Triều', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22205501', 'THCS Nguyễn Huệ', 'Công lập', 'THCS', 'THCS', 'Phường Đông Triều', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22196506', 'THCS Nguyễn Trãi', 'Công lập', 'THCS', 'THCS', 'Phường Uông Bí', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22193503', 'THCS Nguyễn Trãi', 'Công lập', 'THCS', 'THCS', 'Phường Việt Hưng', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22193510', 'THCS Nguyễn Văn Thuộc', 'Công lập', 'THCS', 'THCS', 'Phường Hà Lầm', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22206518', 'THCS Phong Cốc', 'Công lập', 'THCS', 'THCS', 'Phường Phong Cốc', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22201501', 'THCS Quảng Hà', 'Công lập', 'THCS', 'THCS', 'Xã Quảng Hà', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22206501', 'THCS Trần Hưng Đạo', 'Công lập', 'THCS', 'THCS', 'Phường Quảng Yên', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22196505', 'THCS Trần Quốc Toản - Uông Bí', 'Công lập', 'THCS', 'THCS', 'Phường Uông Bí', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22193511', 'THCS Trọng Điểm', 'Công lập', 'THCS', 'THCS', 'Phường Hạ Long', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22204501', 'THCS Trới', 'Công lập', 'THCS', 'THCS', 'Phường Hoành Bồ', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22205517', 'THCS Yên Đức', 'Công lập', 'THCS', 'THCS', 'Phường Hoàng Quế', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22000706', 'THCS và THPT Chu Văn An', 'Tư thục', 'THPT', 'THPT', 'Phường Móng Cái 1', 'pho_thong', array['thpt']::public.cap_hoc[], false),
    ('22000843', 'THCS và THPT Hoành Mô', 'Công lập', 'THCS-THPT', 'Trung học', 'Xã Hoành Mô', 'pho_thong', array['thcs', 'thpt']::public.cap_hoc[], true),
    ('22000818', 'THCS và THPT Hải Đông', 'Công lập', 'THCS-THPT', 'Trung học', 'Xã Đông Ngũ', 'pho_thong', array['thcs', 'thpt']::public.cap_hoc[], true),
    ('22000820', 'THCS và THPT Quan Lạn', 'Công lập', 'THCS-THPT', 'Trung học', 'Đặc khu Vân Đồn', 'pho_thong', array['thcs', 'thpt']::public.cap_hoc[], true),
    ('22000819', 'THCS và THPT Quảng La', 'Công lập', 'THCS-THPT', 'Trung học', 'Xã Quảng La', 'pho_thong', array['thcs', 'thpt']::public.cap_hoc[], true),
    ('22000707', 'THCS và THPT Tiên Yên', 'Công lập', 'THCS-THPT', 'Trung học', 'Xã Tiên Yên', 'pho_thong', array['thcs', 'thpt']::public.cap_hoc[], true),
    ('22000844', 'THCS và THPT Đường Hoa Cương', 'Công lập', 'THCS-THPT', 'Trung học', 'Xã Đường Hoa', 'pho_thong', array['thcs', 'thpt']::public.cap_hoc[], true),
    ('22203501', 'THCS Đông Xá', 'Công lập', 'THCS', 'THCS', 'Đặc khu Vân Đồn', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22201506', 'THCS Đường Hoa', 'Công lập', 'THCS', 'THCS', 'Xã Đường Hoa', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22200501', 'THCS Đại Bình', 'Công lập', 'THCS', 'THCS', 'Xã Đầm Hà', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22200502', 'THCS Đầm Hà', 'Công lập', 'THCS', 'THCS', 'Xã Đầm Hà', 'pho_thong', array['thcs']::public.cap_hoc[], true),
    ('22000740', 'THPT Ba Chẽ', 'Công lập', 'THPT', 'THPT', 'Xã Ba Chẽ', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000712', 'THPT Bãi Cháy', 'Công lập', 'THPT', 'THPT', 'Phường Bãi Cháy', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000703', 'THPT Bình Liêu', 'Công lập', 'THPT', 'THPT', 'Xã Bình Liêu', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000735', 'THPT Bạch Đằng', 'Công lập', 'THPT', 'THPT', 'Phường Quảng Yên', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000F01', 'THPT Chuyên Hạ Long', 'Công lập', 'THPT', 'THPT', 'Phường Hạ Long', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000741', 'THPT Cô Tô', 'Công lập', 'THPT', 'THPT', 'Đặc khu Cô Tô', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000731', 'THPT Cẩm Phả', 'Công lập', 'THPT', 'THPT', 'Phường Cẩm Phả', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000729', 'THPT Cửa Ông', 'Công lập', 'THPT', 'THPT', 'Phường Cửa Ông', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000724', 'THPT Hoàng Hoa Thám', 'Công lập', 'THPT', 'THPT', 'Phường Hoàng Quế', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000723', 'THPT Hoàng Quốc Việt', 'Công lập', 'THPT', 'THPT', 'Phường Mạo Khê', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000739', 'THPT Hoàng Văn Thụ', 'Công lập', 'THPT', 'THPT', 'Phường Vàng Danh', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000702', 'THPT Hoành Bồ', 'Công lập', 'THPT', 'THPT', 'Phường Hoành Bồ', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000811', 'THPT Hòn Gai', 'Công lập', 'THCS-THPT', 'Trung học', 'Phường Hạ Long', 'pho_thong', array['thcs', 'thpt']::public.cap_hoc[], true),
    ('22000747', 'THPT Hùng Vương', 'Tư thục', 'THPT', 'THPT', 'Phường Cửa Ông', 'pho_thong', array['thpt']::public.cap_hoc[], false),
    ('22000716', 'THPT Hạ Long', 'Tư thục', 'THPT', 'THPT', 'Phường Cao Xanh', 'pho_thong', array['thpt']::public.cap_hoc[], false),
    ('22000738', 'THPT Hải Đảo', 'Công lập', 'THPT', 'THPT', 'Đặc khu Vân Đồn', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000709', 'THPT Hồng Đức', 'Tư thục', 'THPT', 'THPT', 'Phường Uông Bí', 'pho_thong', array['thpt']::public.cap_hoc[], false),
    ('22000722', 'THPT Lê Chân', 'Công lập', 'THPT', 'THPT', 'Phường Đông Triều', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000732', 'THPT Lê Quý Đôn', 'Công lập', 'THPT', 'THPT', 'Phường Quang Hanh', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000742', 'THPT Lý Thường Kiệt', 'Công lập', 'THPT', 'THPT', 'Xã Hải Ninh', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000733', 'THPT Lương Thế Vinh', 'Tư thục', 'THPT', 'THPT', 'Phường Cẩm Phả', 'pho_thong', array['thpt']::public.cap_hoc[], false),
    ('22000734', 'THPT Minh Hà', 'Công lập', 'THPT', 'THPT', 'Phường Phong Cốc', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000728', 'THPT Mông Dương', 'Công lập', 'THPT', 'THPT', 'Phường Mông Dương', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000815', 'THPT Nguyễn Bình', 'Tư thục', 'THPT', 'THPT', 'Phường Đông Triều', 'pho_thong', array['thpt']::public.cap_hoc[], false),
    ('22000750', 'THPT Nguyễn Du', 'Tư thục', 'THPT', 'THPT', 'Xã Quảng Hà', 'pho_thong', array['thpt']::public.cap_hoc[], false),
    ('22000727', 'THPT Nguyễn Trãi', 'Tư thục', 'THPT', 'THPT', 'Xã Tiên Yên', 'pho_thong', array['thpt']::public.cap_hoc[], false),
    ('22000751', 'THPT Nguyễn Tất Thành', 'Tư thục', 'THPT', 'THPT', 'Phường Yên Tử', 'pho_thong', array['thpt']::public.cap_hoc[], false),
    ('22000745', 'THPT Ngô Gia Tự', 'Tư thục', 'THPT', 'THPT', 'Phường Liên Hòa', 'pho_thong', array['thpt']::public.cap_hoc[], false),
    ('22000714', 'THPT Ngô Quyền', 'Công lập', 'THPT', 'THPT', 'Phường Cao Xanh', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000705', 'THPT Quảng Hà', 'Công lập', 'THPT', 'THPT', 'Xã Quảng Hà', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000746', 'THPT Thống Nhất', 'Tư thục', 'THPT', 'THPT', 'Xã Thống Nhất', 'pho_thong', array['thpt']::public.cap_hoc[], false),
    ('22000725', 'THPT Trần Nhân Tông', 'Tư thục', 'THPT', 'THPT', 'Phường Mạo Khê', 'pho_thong', array['thpt']::public.cap_hoc[], false),
    ('22000704', 'THPT Trần Phú', 'Công lập', 'THPT', 'THPT', 'Phường Móng Cái 2', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000710', 'THPT Trần Quốc Tuấn', 'Tư thục', 'THPT', 'THPT', 'Phường Đông Mai', 'pho_thong', array['thpt']::public.cap_hoc[], false),
    ('22000708', 'THPT Uông Bí', 'Công lập', 'THPT', 'THPT', 'Phường Uông Bí', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000713', 'THPT Vũ Văn Hiếu', 'Công lập', 'THPT', 'THPT', 'Phường Hà Tu', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000736', 'THPT Đông Thành', 'Công lập', 'THPT', 'THPT', 'Phường Đông Mai', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000721', 'THPT Đông Triều', 'Công lập', 'THPT', 'THPT', 'Phường Đông Triều', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22000701', 'THPT Đầm Hà', 'Công lập', 'THPT', 'THPT', 'Xã Đầm Hà', 'pho_thong', array['thpt']::public.cap_hoc[], true),
    ('22202401', 'Tiểu học Ba Chẽ', 'Công lập', 'TH', 'Tiểu học', 'Xã Ba Chẽ', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22193405', 'Tiểu học Bãi Cháy', 'Công lập', 'TH', 'Tiểu học', 'Phường Bãi Cháy', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22205407', 'Tiểu học Bình Khê', 'Công lập', 'TH', 'Tiểu học', 'Phường Bình Khê', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22193409', 'Tiểu học Cao Thắng', 'Công lập', 'TH', 'Tiểu học', 'Phường Hà Lầm', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22203406', 'Tiểu học Cái Rồng', 'Công lập', 'TH', 'Tiểu học', 'Đặc khu Vân Đồn', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22195415', 'Tiểu học Cẩm Phả', 'Công lập', 'TH', 'Tiểu học', 'Phường Cẩm Phả', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22195409', 'Tiểu học Cẩm Sơn', 'Công lập', 'TH', 'Tiểu học', 'Phường Cửa Ông', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22195404', 'Tiểu học Cửa Ông', 'Công lập', 'TH', 'Tiểu học', 'Phường Cửa Ông', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22205420', 'Tiểu học Hoàng Quế', 'Công lập', 'TH', 'Tiểu học', 'Phường Hoàng Quế', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22206411', 'Tiểu học Hà An', 'Công lập', 'TH', 'Tiểu học', 'Phường Hà An', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22206410', 'Tiểu học Hà An 1', 'Công lập', 'TH', 'Tiểu học', 'Phường Hà An', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22193411', 'Tiểu học Hà Lầm', 'Công lập', 'TH', 'Tiểu học', 'Phường Hà Lầm', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22203402', 'Tiểu học Hạ Long', 'Công lập', 'TH', 'Tiểu học', 'Đặc khu Vân Đồn', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22195412', 'Tiểu học Hồ Tùng Mậu', 'Công lập', 'TH', 'Tiểu học', 'Phường Cẩm Phả', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22193406', 'Tiểu học Hồng Gai', 'Công lập', 'TH', 'Tiểu học', 'Phường Hồng Gai', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22194417', 'Tiểu học Ka Long', 'Công lập', 'TH', 'Tiểu học', 'Phường Móng Cái 2', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22205410', 'Tiểu học Kim Đồng', 'Công lập', 'TH', 'Tiểu học', 'Phường Đông Triều', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22206416', 'Tiểu học Liên Hòa', 'Công lập', 'TH', 'Tiểu học', 'Phường Liên Hòa', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22205411', 'Tiểu học Lê Hồng Phong', 'Công lập', 'TH', 'Tiểu học', 'Phường Đông Triều', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22193404', 'Tiểu học Lý Thường Kiệt', 'Công lập', 'TH', 'Tiểu học', 'Phường Việt Hưng', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22194407', 'Tiểu học Lý Tự Trọng', 'Công lập', 'TH', 'Tiểu học', 'Phường Móng Cái 1', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22194404', 'Tiểu học Móng Cái 2', 'Công lập', 'TH', 'Tiểu học', 'Phường Móng Cái 2', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22205417', 'Tiểu học Mạo Khê', 'Công lập', 'TH', 'Tiểu học', 'Phường Mạo Khê', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22205413', 'Tiểu học Mạo Khê I', 'Công lập', 'TH', 'Tiểu học', 'Phường Mạo Khê', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22205415', 'Tiểu học Mạo Khê II', 'Công lập', 'TH', 'Tiểu học', 'Phường Mạo Khê', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22205416', 'Tiểu học Mạo Khê III', 'Công lập', 'TH', 'Tiểu học', 'Phường Mạo Khê', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22206407', 'Tiểu học Nguyễn Bình', 'Công lập', 'TH', 'Tiểu học', 'Phường Quảng Yên', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22195402', 'Tiểu học Nguyễn Trãi', 'Công lập', 'TH', 'Tiểu học', 'Phường Mông Dương', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22206406', 'Tiểu học Nguyễn Văn Thuần', 'Công lập', 'TH', 'Tiểu học', 'Phường Hiệp Hòa', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22206401', 'Tiểu học Ngô Quyền', 'Công lập', 'TH', 'Tiểu học', 'Phường Quảng Yên', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22195414', 'Tiểu học Phan Bội Châu', 'Công lập', 'TH', 'Tiểu học', 'Phường Cẩm Phả', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22206511', 'Tiểu học Phong Cốc I', 'Công lập', 'TH', 'Tiểu học', 'Phường Phong Cốc', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22206420', 'Tiểu học Phong Cốc II', 'Công lập', 'TH', 'Tiểu học', 'Phường Phong Cốc', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22196416', 'Tiểu học Phương Đông', 'Công lập', 'TH', 'Tiểu học', 'Phường Yên Tử', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22205422', 'Tiểu học Phạm Hồng Thái', 'Công lập', 'TH', 'Tiểu học', 'Phường Hoàng Quế', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22193412', 'Tiểu học Quang Trung - Hạ Long', 'Công lập', 'TH', 'Tiểu học', 'Phường Hạ Long', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22196409', 'Tiểu học Quang Trung - Uông Bí', 'Công lập', 'TH', 'Tiểu học', 'Phường Uông Bí', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22201401', 'Tiểu học Quảng Hà', 'Công lập', 'TH', 'Tiểu học', 'Xã Quảng Hà', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22196412', 'Tiểu học Thanh Sơn', 'Công lập', 'TH', 'Tiểu học', 'Phường Uông Bí', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22205403', 'Tiểu học Thủy An', 'Công lập', 'TH', 'Tiểu học', 'Phường Đông Triều', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22199401', 'Tiểu học Tiên Yên', 'Công lập', 'TH', 'Tiểu học', 'Xã Tiên Yên', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22193407', 'Tiểu học Trần Hưng Đạo', 'Công lập', 'TH', 'Tiểu học', 'Phường Hồng Gai', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22193413', 'Tiểu học Trần Quốc Toản', 'Công lập', 'TH', 'Tiểu học', 'Phường Hạ Long', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22204401', 'Tiểu học Trới', 'Công lập', 'TH', 'Tiểu học', 'Phường Hoành Bồ', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22198405', 'Tiểu học Tình Húc', 'Công lập', 'TH', 'Tiểu học', 'Xã Bình Liêu', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22195407', 'Tiểu học Võ Thị Sáu', 'Công lập', 'TH', 'Tiểu học', 'Phường Cửa Ông', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22194406', 'Tiểu học Đào Phúc Lộc', 'Công lập', 'TH', 'Tiểu học', 'Phường Móng Cái 1', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22199403', 'Tiểu học Đông Ngũ', 'Công lập', 'TH', 'Tiểu học', 'Xã Đông Ngũ', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22203401', 'Tiểu học Đông Xá', 'Công lập', 'TH', 'Tiểu học', 'Đặc khu Vân Đồn', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22201408', 'Tiểu học Đường Hoa', 'Công lập', 'TH', 'Tiểu học', 'Xã Đường Hoa', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22200401', 'Tiểu học Đại Bình', 'Công lập', 'TH', 'Tiểu học', 'Xã Đầm Hà', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22200403', 'Tiểu học Đầm Hà', 'Công lập', 'TH', 'Tiểu học', 'Xã Đầm Hà', 'pho_thong', array['tieu_hoc']::public.cap_hoc[], true),
    ('22000A01', 'Trung tâm GDNN-GDTX tỉnh Quảng Ninh,', 'GDTX', 'GDTX', 'THPT', 'Phường Hà Lầm', 'gdtx', array['gdtx']::public.cap_hoc[], true)
)
insert into public.co_so_giao_duc(
  ma_truong, ten, loai_hinh, cap_hoc, cong_lap, dia_chi, co_quan_quan_ly,
  tinh_thanh, phuong_xa, loai_hinh_dao_tao, loai_hinh_truong,
  nguon_danh_muc, cho_phep_tu_dang_ky
)
select
  source.ma_truong,
  source.ten,
  source.loai_hinh::public.loai_hinh_co_so,
  source.cap_hoc,
  source.cong_lap,
  source.phuong_xa || ', Quảng Ninh',
  'Sở Giáo dục và Đào tạo Quảng Ninh',
  'Quảng Ninh',
  source.phuong_xa,
  source.loai_hinh_dao_tao,
  source.loai_hinh_truong,
  'MOET',
  true
from source
on conflict (ma_truong) do update
set ten = excluded.ten,
    cong_lap = excluded.cong_lap,
    dia_chi = excluded.dia_chi,
    co_quan_quan_ly = excluded.co_quan_quan_ly,
    tinh_thanh = excluded.tinh_thanh,
    phuong_xa = excluded.phuong_xa,
    loai_hinh_dao_tao = excluded.loai_hinh_dao_tao,
    loai_hinh_truong = excluded.loai_hinh_truong,
    nguon_danh_muc = excluded.nguon_danh_muc,
    cho_phep_tu_dang_ky = true,
    loai_hinh = case
      when not exists (
        select 1 from public.nam_hoc school_year
        where school_year.co_so_id = co_so_giao_duc.id
      ) then excluded.loai_hinh
      else co_so_giao_duc.loai_hinh
    end,
    cap_hoc = case
      when not exists (
        select 1 from public.nam_hoc school_year
        where school_year.co_so_id = co_so_giao_duc.id
      ) then excluded.cap_hoc
      else co_so_giao_duc.cap_hoc
    end,
    updated_at = now();

insert into public.nam_hoc(
  co_so_id, ten, ngay_bat_dau, ngay_ket_thuc, trang_thai, bo_tieu_chuan_id
)
select
  school.id,
  '2026-2027',
  '2026-09-01'::date,
  '2027-05-31'::date,
  case
    when exists (
      select 1 from public.nam_hoc active_year
      where active_year.co_so_id = school.id
        and active_year.trang_thai = 'dang_hoat_dong'
    ) then 'chuan_bi'::public.trang_thai_nam_hoc
    else 'dang_hoat_dong'::public.trang_thai_nam_hoc
  end,
  standard_set.id
from public.co_so_giao_duc school
join lateral (
  select standard.id
  from public.bo_tieu_chuan standard
  where standard.loai_hinh = school.loai_hinh
    and standard.trang_thai = 'dang_ap_dung'
    and (standard.ngay_hieu_luc is null or standard.ngay_hieu_luc <= '2027-05-31'::date)
  order by standard.ngay_hieu_luc desc nulls last, standard.version desc, standard.created_at desc
  limit 1
) standard_set on true
where school.cho_phep_tu_dang_ky
  and school.tinh_thanh = 'Quảng Ninh'
on conflict (co_so_id, ten) do nothing;

commit;
